#spring:
#  datasource:
#    url: jdbc:mysql://8.134.24.31:3306/juejin?useUnicode=true&characterEncoding=utf8&useSSL=false
#    #因为稀土掘金的网址是拼音，所以数据库名也是拼音
#    username: root
#    password: nopassword
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  data:
#    redis:
#      host: 8.134.24.31
#      port: 6379
#      database: 0
#      password: nopassword
#上面的配置是旧服务器的配置，程序写到一半发现旧服务器快过期了，就换了一个服务器


spring:
  datasource:
    url: jdbc:mysql://8.134.219.139:3306/juejin?useUnicode=true&characterEncoding=utf8&useSSL=false
    #因为稀土掘金的网址是拼音，所以数据库名也是拼音
    username: root
    password: nopassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    encoding:
      charset: UTF-8
      enabled: force
      force: true
  data:
    redis:
      host: 8.134.219.139
      port: 6379
      database: 0
      password: nopassword


jwt:
  secret: ashduiahdwhadgreaIUEHiuhiHHAWd8hilhOAWDjho8WAUYHDo8h3hukaHDIWAHihDAW78928ADyw8h289AHD892h98AHD8929hdfsAWHD892
  expiration: 3600000  # 令牌过期时间，单位是毫秒
  tokenHeader: Authorization
  tokenHead: 'Bearer '
#3600000
server:
  port: 6666
qsadxs:
  defaultAvatar: /9j/4AAQSkZJRgABAQEAYABgAAD/4gIoSUNDX1BST0ZJTEUAAQEAAAIYAAAAAAIQAABtbnRyUkdCIFhZWiAAAAAAAAAAAAAAAABhY3NwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAA9tYAAQAAAADTLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlkZXNjAAAA8AAAAHRyWFlaAAABZAAAABRnWFlaAAABeAAAABRiWFlaAAABjAAAABRyVFJDAAABoAAAAChnVFJDAAABoAAAAChiVFJDAAABoAAAACh3dHB0AAAByAAAABRjcHJ0AAAB3AAAADxtbHVjAAAAAAAAAAEAAAAMZW5VUwAAAFgAAAAcAHMAUgBHAEIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFhZWiAAAAAAAABvogAAOPUAAAOQWFlaIAAAAAAAAGKZAAC3hQAAGNpYWVogAAAAAAAAJKAAAA+EAAC2z3BhcmEAAAAAAAQAAAACZmYAAPKnAAANWQAAE9AAAApbAAAAAAAAAABYWVogAAAAAAAA9tYAAQAAAADTLW1sdWMAAAAAAAAAAQAAAAxlblVTAAAAIAAAABwARwBvAG8AZwBsAGUAIABJAG4AYwAuACAAMgAwADEANv/bAEMAAwICAwICAwMDAwQDAwQFCAUFBAQFCgcHBggMCgwMCwoLCw0OEhANDhEOCwsQFhARExQVFRUMDxcYFhQYEhQVFP/bAEMBAwQEBQQFCQUFCRQNCw0UFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFP/AABEIAEAAQAMBIgACEQEDEQH/xAAfAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgv/xAC1EAACAQMDAgQDBQUEBAAAAX0BAgMABBEFEiExQQYTUWEHInEUMoGRoQgjQrHBFVLR8CQzYnKCCQoWFxgZGiUmJygpKjQ1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4eLj5OXm5+jp6vHy8/T19vf4+fr/xAAfAQADAQEBAQEBAQEBAAAAAAAAAQIDBAUGBwgJCgv/xAC1EQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2gAMAwEAAhEDEQA/AP1S/Ciiua+JHxD0X4UeB9X8WeIZ2t9I0yISzNGu5zlgqqo7szMqj3IoA6WuL8XfGbwT4IWZNV8S6bHexkKNOjuUku5GJwqpCDvYkn09zgAmvy//AGiP2/PHPxgurnTfDlxceDPCh3IttZSlbu5U8ZmmXkZH8CYHJBLda5T9mW1s5v7YurZTL4kj4Vtis8cJ2gsm7+I/PjPGRg9RXNiK3sabna5vSpe0kotn61+Bfi94X+IkkkOkagDex7t1ncL5cvyna2AeG2kEEqTg9eors/wr8o9Q1i20TRNV1G71W0stSsrS6mhuI7j7POlyIzsePdtlDqwfnAIMnGa6v9jf9tjXdR8XWPhX4j+KbvUdJmmSW01SZgXjcKyiOWVSGaNmZDlt3K88E4xwuJdaLc1Zo1qYdqSjT1ufpjmkPQ8UUxZo5fMCOrlDtYA9D6V3XV7HGS18v/8ABSLUorP9lbXrVpEWW9vbGKONnAZ9tzHIQo6scJ0HbntX1Aa/On/got4B8RD4reGfFupeI5LvwssTRWOki0ZY7OQKAw8zlXZ255w3QAELmhlwXNJI+ELHwjq+p2/2gqthakfI0vLuTwoA9z6+vWu90P4IalY+HB4ivLe9ufDl1N9j+3kPFDNMBu2qQ2WXg8/dypHWu3+Gt2I/Enh6NZ7CASXcNnNdahbpcRWiu4jkmKOCpaMMzrv+UMgzwDX1n4b8I+IZPi1d+GtZXWvFPh24u7izuI9alknt5LIFikoOBGhAWNwUC/NwMEjHNUqclrnr0ML7XmcWvdV9X+C8z4mt/Bdn5F19h0eB4ra3M0rJAHMahlXce+MuoznuK5fVvCv/AAk+j2k2hQWsGs/aEiikjK26OzOE+ctwq8gndwBnPevv74sfsu2Hw8jsdV8Bf27Ld3d0bS4sIZ/NxBJHIMJhfM+/5YzuJAOfU1hW/wDwTw8T6xpsksmtaVojT21vjT5I3nMcggjWQO69cyK5zluDjoAKUaqm2krlSp8tNVeZK97a66W1Pt74fafrGkeBfD1j4iuYL3XrbT4Ib+4tkCRSTrGokZFAAClgcYA+greIABwAO9cL8ItI17wd4L0nw74q1Ztc1m0gCHUNgVZVHAA7naMDLfMcZPWu67GupO54souLsONfFf7fXxetJo7D4fafcLLPDIt/qhR/9V8p8qJsdyGLkHoNh/ir7QuvO+yzfZ9vn7G8vf8Ad3Y4z7Zr8dPiFoXibSvGXimx8WR3Nv4kmuXlumvOXdnQfvARwykgkFflx06YCZvQjzSv2Oj+NHhGw8GfBv4Ra/FpVsmra5FqL3rfcaeNbjMEjcckIy4PoR7Vd0n9rrx5L8OdU0XT4dC8Ppb2ZiE2mWPlvOxRgN2WKhiqEfIq8nIGBivQf20LfQPGHwN+D3iDwheG7s7Jm0GGwxmZWNursGHXcn2fDYH8YI4r5C8P6pqmhtPHtzJcExFYwyDuDuyeg3ZPTAB5AzXPVimvM2hJ21Prf9lb9rLRbexsdJurLVdQ+JWp3gt4JkgjexcO/wB5YYym19vy52n1LYJFfdHxItfFlnaWmseDNM03U9fhdVmttSneJJISpDBCDgNkg89s1+bv/BOTwNY/8NHRSanMjXGlafcS2UYwQ0w2p1BIJ2PI3H93Nfq5ShTi4yjF2XkXUrSjOFSau7dbu/TXU5oWeopatq0/2gXcyW8kmleas0Vq4wJPLYKCflJz2O3IAJOekjkWWEOh3KwyCK+TPiF+2vpFn8bNB8L6T5t34ct7jytVv7ckGVmYRgxEEErGxBPXdzgHgn6zjjWGPYowqjitob6HLVTVuZWY+vMPid+zn4J+L2t22r+IrS6l1CCEW6yQ3boDGCSFK5xwWJ4weea9O696T8RWpgm1qj8kv24tSi8A/FLw98PPBkstlpXha23ffUvJeXR3yyMxwAdnlAYACgcYHFcbpPgP4ieOvHlrpFppOoKb2NYba+1G0aERK7ITKW4DhBk5Tg7cjOef02/4ZT8D+IfEV3rvjDRLfxHqTXs11B9qmeSKMSkMwMeFU/NuwGDYGBmql34K+Mlj40ttN0S78Bw/DaCSGNWu7W6Or/Zl27kyhEe4AFVb0AJ5yK53Tcndm6qKKsrnwx4T/Z1+L/w++L1hBYanp2laxpNwA19a3D3D3O1iVf7LCHlKFCPvoAQx3Njp9wfDT9oW8+JngzX7bUvC+qWPiDTHl069jsoN2JhuQOI2ZXQMVJCnp03V3fxM8G+NNcCy+AvGNj4Lv5gFvLm+0f8AtISKv3CkZmjVXGSCxzkYGPlFP+GPwxuPAcRutS16TXtfu4iNUv1tIrSO+mMjP5xiQYUjcVGCeOuaTpO94u1zWOIXKozje2x5J+zv+yBpXw11YeINZ+x67Psjk0+K9sGFxpzgg8N5pRiMDnYGBGQR0r6Y9fpS/jSfwnntW6VlY5Zyc5OTP//Z
